name: Decompress Playlist

on:
  push:
    branches:
      - main
    paths:
      - 'generated/IPTV_HUB.m3u.gz'

permissions:
  contents: write

jobs:
  decompress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Remove old playlist
        run: rm -f generated/IPTV_HUB.m3u

      - name: Decompress new playlist
        run: |
          gunzip -f generated/IPTV_HUB.m3u.gz

          sed -i \
          -e 's/ tvg-id=""//g' \
          -e 's/ tvg-name=""//g' \
          -e 's/ tvg-logo=""//g' \
          -e 's/ group-title=""//g' \
          generated/IPTV_HUB.m3u

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add generated/IPTV_HUB.m3u
          git diff --staged --quiet || git commit -m "Auto-decompress IPTV playlist"
          git push
